### ISSUE TITLE
Patch proposal

### ISSUE THREAD

**Issue by gslongo** [FastSociety/nagios-nvidia-smi-plugin#1]
Hi,

Here is a patch allowing to choose the device and also handle GPU temperature.

(the link is valid for 60 days)
<a href='https://cloudbox.it-optics.com/pydio/data/public/7cdf313f336ba1f8064e6a180d4a84c0--en?dl=true&file=/a5b6eeb2e4/check_nvidiasmi.py.diff'>Download check_nvidiasmi.py.diff</a>

Thank you for your work,

Best regards

**Comment by wilrnh** [comment]
Thanks! re: #2 

Included in release 0.4.0!
